### ISSUE TITLE
上传20多兆的文件后，页面卡住点不开？

### ISSUE THREAD

**Issue by 0nmyway** [HatBoy/Pcap-Analyzer#11]
ARNING: Unless called manually, this could indicate deprecated use. Should be changed to bytes(self)
WARNING: more Unless called manually, this could indicate deprecated use. Should be changed to bytes(self)
WARNING: Unless called manually, this could indicate deprecated use. Should be changed to bytes(self)
WARNING: Unless called manually, this could indicate deprecated use. Should be changed to bytes(self)
WARNING: more Unless called manually, this could indicate deprecated use. Should be changed to bytes(self)

**Comment by HatBoy** [comment]
该工具分析的数据包全部是在内存中进行操作的，20M的数据包在内存中展开建立索引可能占用2G的内存，而且分析起来比较慢，这是该工具的设计上的问题，大文件的分析内存占用大，而且分析慢
