### ISSUE TITLE
gunicorn error

### ISSUE THREAD

**Issue by FreelancePentester** [HatBoy/Pcap-Analyzer#2]
[2016-12-07 15:11:43 +0000] [29478] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f8337caa938>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f8337caa668>
  pre_fork: <function pre_fork at 0x7f8337caa7d0>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: gunicorn.pid
  sendfile: None
  pidfile: /var/log/gunicorn/debug.log
  umask: 0
  on_reload: <function on_reload at 0x7f8337caa500>
  pre_exec: <function pre_exec at 0x7f8337caaed8>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f8337caaaa0>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f8337cad5f0>
  config: deploy_config.py
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f8337cad0c8>
  post_request: <function post_request at 0x7f8337cad1b8>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f8337caac08>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f8337cad320>
  chdir: /home/ddos/Downloads/Pcap-Analyzer
  paste: None
  default_proc_name: run:
  errorlog: -
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f8337caa398>
  worker_abort: <function worker_abort at 0x7f8337caad70>
  bind: ['0.0.0.0:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f8337cad488>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2016-12-07 15:11:43 +0000] [29478] [INFO] Starting gunicorn 19.6.0

Error: /var/log/gunicorn doesn't exist. Can't create pidfile.

**Comment by HatBoy** [comment]
/var/log/gunicorn doesn't exist

**Comment by FreelancePentester** [comment]
Thanks but 
python: ../../../texk/kpathsea/progname.c:316: remove_dots: Assertion `ret' failed.
[2016-12-07 21:30:24 +0000] [12084] [DEBUG] 0 workers
[2016-12-07 21:30:24 +0000] [12430] [INFO] Booting worker with pid: 12430
lstat(./dvips) failed ...
./dvips: No such file or directory

**Comment by HatBoy** [comment]
@FreelancePentester I thanks you have something  dependency library can not install , is not my application error, is you system environment error, maybe you can reference gunicorn doc

**Comment by m4k2k** [comment]
I had the same errors as mentioned above. Creating the folder resolved the first problem (missing folder). Then I had a google translator problem. g'translator broke/transformed the command "gunicorn -c deploy_config.py **run:app**" to "gunicorn -c deploy_config.py **run: app**".
Removing the space fixed the problem. (just in case someone else encounters it)

**Comment by EniacTNB** [comment]
> 

That's worked
