### ISSUE TITLE
gunicorn -c deploy_config.py run:app 报错

### ISSUE THREAD

**Issue by liko330** [HatBoy/Pcap-Analyzer#21]
您好，
环境python3.5+Ubuntu1604
按照文档说明使用pip3 install scapy-python3命令安装scapy
其余部分按文档安装好后，执行gunicorn -c deploy_config.py run:app 报错：
Exception: 
        PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene. 
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).  
请教一下该如何解决

**Comment by HatBoy** [comment]
@liko330 这个问题涉及到scapy库的历史原因，原来的scapy库只支持Python2，后来在我编写该程序的时候Scapy起了一个分支支持Python3，需要通过scapy-python3来安装，后来两个分支合并了，现在直接通过pip3 install scapy安装即可

**Comment by liko330** [comment]
重新安装scapy后可以使用了，感谢
