### ISSUE TITLE
项目能跑起来，但是文件可以上传，但无法分析出结果．在scapy 的haslayer方法传参TCP IP报编译错误

### ISSUE THREAD

**Issue by hilbertfeng** [HatBoy/Pcap-Analyzer#22]

**Comment by hilbertfeng** [comment]
用pip3安装了scapy,但是运行项目的时候报错，说找不到scapy.all 模块，所以查找了一下用到scapy的属性和方法都是在scapy.utils里面，所以我把项目的scapy.all 改成了scapy.utils项目就正常运行了，但是无法运行出分析结果。
我用的开发工具是pycharm python3.5 和３．6都试了一遍
下面是控制台打印的运行结果
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
127.0.0.1 - - [19/Jan/2019 15:43:59] "GET /static/img/loading.gif HTTP/1.1" 404 -
127.0.0.1 - - [19/Jan/2019 15:44:03] "GET /ftpfile/ HTTP/1.1" 302 -
/home/tarena/PycharmProjects/pcap-Analysis/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  upload = Upload()
127.0.0.1 - - [19/Jan/2019 15:44:03] "GET /upload/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Jan/2019 15:44:10] "GET /static/img/loading.gif HTTP/1.1" 404 -
/home/tarena/PycharmProjects/pcap-Analysis/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  upload = Upload()
127.0.0.1 - - [19/Jan/2019 15:44:13] "POST /upload/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Jan/2019 15:44:24] "GET /ftpdata/ HTTP/1.1" 302 -
/home/tarena/PycharmProjects/pcap-Analysis/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  upload = Upload()

**Comment by HatBoy** [comment]
@hilbertfeng 你是怎么安装scapy的，我目前用的scapy还是可以正常使用的，而且我查看官方文档，并没有说明将scapy.all更改为scapy.utils的说明，scapy的安装请参照官方文档

**Comment by hilbertfeng** [comment]
@HatBoy 可以了，谢谢。我的Linux系统少了一些依赖文件
