### ISSUE TITLE
网站能在本机打开，但是上传文件会提示“上传错误,错误信息:[Errno 2] No such file or directory：xxxxxx”

### ISSUE THREAD

**Issue by yuluo-ding** [HatBoy/Pcap-Analyzer#23]
系统是macOS，Python3.7，依赖都已经装好。
目前是可以本机运行，但是在选择数据包的时候，无法上传。无论是我自己的数据包，还是项目本身里面提供的案例数据包。
在运行的时候，会提示：
`FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.     upload = Upload()`这个warning。

额外一点：

1. 关于scapy的一些导入，`from scapy.all import *` 这个没用，until下的几个文件会报错，需要具体的导入，比如：
    ```python
    from scapy.layers.dns import DNS
    from scapy.layers.inet import IP, TCP, UDP, ICMP
    from scapy.layers.inet6 import IPv6
    from scapy.layers.l2 import ARP
    ```

望解答回复，谢谢🙏️。

**Comment by HatBoy** [comment]
@yuluo-ding 关于第一个上传失败的问题，其实比较明显，首先需要在配置文件里面修改你需要上传的目录，这些目录是你自己手动创建的，可参考readme，然后这个报错的原因就是上传用的第三方插件目前已经不支持这个函数了，你可以修改源码，或者使用低版本的上传插件。第二个问题就是scapy的导入方式是官方提供的导入方式，刚刚测试还是可以用的，你说的报错应该是编译器显示报错，运行过程中是不会报错的

**Comment by yuluo-ding** [comment]
根据建议，基本能运行起来。谢谢🙏️
