### ISSUE TITLE
作者

### ISSUE THREAD

**Issue by namedjmd** [HatBoy/Pcap-Analyzer#25]
如题。

**Comment by HatBoy** [comment]
@namedjmd 什么意思？

**Comment by namedjmd** [comment]
抱歉。这里操作出现了失误。我重新编辑过，不知道为什么没有更新过来。
我是想向楼主了解下，这个工具能否修改pcap包的内容，比如ip，mac，这些信息。

**Comment by HatBoy** [comment]
@namedjmd 这个工具只用作分析不用做修改pcap包内容，但是底层使用的scapy库是具有修改数据包功能的，有兴趣的话，可以参考scapy自己实现，还是比较简单的
