### ISSUE TITLE
 /var/log/gunicorn doesn't exist. Can't create pidfile.

### ISSUE THREAD

**Issue by shipeng220** [HatBoy/Pcap-Analyzer#26]
[2019-09-22 20:11:51 +0800] [2670] [DEBUG] Current configuration:
  pre_fork: <function Prefork.pre_fork at 0x7f59867499d8>
  syslog: False
  reuse_port: False
  daemon: False
  pidfile: /var/log/gunicorn/debug.log
  proxy_allow_ips: ['127.0.0.1']
  disable_redirect_access_to_syslog: False
  secure_scheme_headers: {'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on', 'X-FORWARDED-PROTOCOL': 'ssl'}
  on_reload: <function OnReload.on_reload at 0x7f59867497b8>
  child_exit: <function ChildExit.child_exit at 0x7f598625b268>
  loglevel: debug
  limit_request_fields: 100
  reload_extra_files: []
  ssl_version: 2
  reload_engine: auto
  check_config: False
  raw_env: []
  worker_tmp_dir: None
  user: 1000
  proxy_protocol: False
  logconfig: None
  workers: 1
  worker_class: sync
  preload_app: False
  post_fork: <function Postfork.post_fork at 0x7f5986749ae8>
  config: deploy_config.py
  certfile: None
  enable_stdio_inheritance: False
  initgroups: False
  tmp_upload_dir: None
  do_handshake_on_connect: False
  ciphers: TLSv1
  bind: ['0.0.0.0:8000']
  statsd_prefix: 
  pythonpath: None
  worker_connections: 1000
  max_requests_jitter: 0
  timeout: 30
  spew: False
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f598625b488>
  chdir: /home/shipeng/Pcap-Analyzer-master
  paste: None
  worker_exit: <function WorkerExit.worker_exit at 0x7f598625b378>
  on_exit: <function OnExit.on_exit at 0x7f598625b598>
  accesslog: None
  capture_output: False
  logconfig_dict: {}
  syslog_prefix: None
  on_starting: <function OnStarting.on_starting at 0x7f59867496a8>
  proc_name: gunicorn.pid
  worker_abort: <function WorkerAbort.worker_abort at 0x7f5986749e18>
  syslog_facility: user
  pre_request: <function PreRequest.pre_request at 0x7f598625b0d0>
  backlog: 2048
  reload: False
  max_requests: 0
  graceful_timeout: 30
  pre_exec: <function PreExec.pre_exec at 0x7f5986749f28>
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  statsd_host: None
  keyfile: None
  forwarded_allow_ips: ['127.0.0.1']
  cert_reqs: 0
  default_proc_name: run:app
  sendfile: None
  keepalive: 2
  errorlog: -
  when_ready: <function WhenReady.when_ready at 0x7f59867498c8>
  worker_int: <function WorkerInt.worker_int at 0x7f5986749d08>
  umask: 0
  ca_certs: None
  suppress_ragged_eofs: True
  limit_request_line: 4094
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f5986749bf8>
  group: 1000
  limit_request_field_size: 8190
  post_request: <function PostRequest.post_request at 0x7f598625b158>
  threads: 1
  raw_paste_global_conf: []
[2019-09-22 20:11:51 +0800] [2670] [INFO] Starting gunicorn 19.9.0

Error: /var/log/gunicorn doesn't exist. Can't create pidfile.

**Comment by shipeng220** [comment]
how to deal with it?

**Comment by HatBoy** [comment]
try https://stackoverflow.com/questions/54793822/error-run-airflow-doesnt-exist-cant-create-pidfile-when-using-systemd-fo

**Comment by shipeng220** [comment]
thanks
| |
石鹏
|
|
邮箱：15298386753@163.com
|

签名由 网易邮箱大师 定制

On 09/24/2019 11:06, HatBoy wrote:

try https://stackoverflow.com/questions/54793822/error-run-airflow-doesnt-exist-cant-create-pidfile-when-using-systemd-fo
