### ISSUE TITLE
数据分析里的基本信息，点击查看数据包详情，全部为空白

### ISSUE THREAD

**Issue by Thewinnerof** [HatBoy/Pcap-Analyzer#28]
![捕获](https://user-images.githubusercontent.com/38658390/68553464-797da080-045c-11ea-935e-4a4f4a947ecd.PNG)

**Comment by Thewinnerof** [comment]
File "/usr/local/lib/python3.7/site-packages/scapy/packet.py", line 659, in canvas_dump
    raise ImportError("PyX and its dependencies must be installed")
ImportError: PyX and its dependencies must be installed

**Comment by HatBoy** [comment]
@Thewinnerof 推测可能有两个原因，一个原因是scapy的版本不对，scapy 2.4之后的版本有了较大的改动，可能导致整个解析出了问题。另一个原因是scapy相关的库没有安装齐全，scapy有很多可选库

**Comment by Thewinnerof** [comment]
好的，谢谢给出的建议，可能scapy库这块出了问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HatBoy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 上午10:38
收件人:&nbsp;"HatBoy/Pcap-Analyzer"<Pcap-Analyzer@noreply.github.com&gt;;
抄送:&nbsp;"1020343877"<1020343877@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HatBoy/Pcap-Analyzer] 数据分析里的基本信息，点击查看数据包详情，全部为空白 (#28)




@Thewinnerof 推测可能有两个原因，一个原因是scapy的版本不对，scapy 2.4之后的版本有了较大的改动，可能导致整个解析出了问题。另一个原因是scapy相关的库没有安装齐全，scapy有很多可选库

**Comment by xiaoyunjie** [comment]
yum install texlive*
pip3 install scapy --upgrade

**Comment by K0zero** [comment]
我也遇到这个问题了，我的pyx已经安装好了。
后来在这个链接https://stackoverflow.com/questions/50914059/pyx-not-installed-correctly-when-using-scapy
需要安装如下东西—— sudo apt install texlive-latex-base  安装好重启即可。
给后面遇到此问题的同志一点帮助
