### ISSUE TITLE
运行命令gunicorn -c deploy_config.py run:app 报错

### ISSUE THREAD

**Issue by gitfuzzing** [HatBoy/Pcap-Analyzer#3]
root@kali:~/Pcap-Analyzer-master# gunicorn -c deploy_config.py run:app
[2017-02-21 10:37:46 +0000] [1843] [DEBUG] Current configuration:
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7ffb27c2cb18>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7ffb27c2c848>
  pre_fork: <function pre_fork at 0x7ffb27c2c9b0>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: gunicorn.pid
  sendfile: None
  pidfile: /var/log/gunicorn/debug.log
  umask: 0
  on_reload: <function on_reload at 0x7ffb27c2c6e0>
  pre_exec: <function pre_exec at 0x7ffb27c34140>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7ffb27c2cc80>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7ffb27c347d0>
  config: deploy_config.py
  logconfig: None
  check_config: False
  statsd_prefix: 
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7ffb27c342a8>
  post_request: <function post_request at 0x7ffb27c34398>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7ffb27c2cde8>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7ffb27c34500>
  chdir: /root/Pcap-Analyzer-master
  paste: None
  default_proc_name: run:app
  errorlog: -
  loglevel: debug
  capture_output: False
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7ffb27c2c578>
  worker_abort: <function worker_abort at 0x7ffb27c2cf50>
  bind: ['0.0.0.0:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7ffb27c34668>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2017-02-21 10:37:46 +0000] [1843] [INFO] Starting gunicorn 19.6.0
[2017-02-21 10:37:46 +0000] [1843] [DEBUG] Arbiter booted
[2017-02-21 10:37:46 +0000] [1843] [INFO] Listening at: http://0.0.0.0:8000 (1843)
[2017-02-21 10:37:46 +0000] [1843] [INFO] Using worker: sync
[2017-02-21 10:37:46 +0000] [1848] [INFO] Booting worker with pid: 1848
[2017-02-21 10:37:47 +0000] [1843] [DEBUG] 1 workers
WARNING: No route found for IPv6 destination :: (no default route?)
[2017-02-21 10:37:49 +0000] [1848] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/root/Pcap-Analyzer-master/run.py", line 4, in <module>
    from app import app
  File "/root/Pcap-Analyzer-master/app/__init__.py", line 11, in <module>
    from app import views
  File "/root/Pcap-Analyzer-master/app/views.py", line 12, in <module>
    from utils.ipmap_tools import getmyip, get_ipmap, get_geo
  File "/root/Pcap-Analyzer-master/app/utils/ipmap_tools.py", line 9, in <module>
    import geoip2.database
ImportError: No module named geoip2.database
[2017-02-21 10:37:49 +0000] [1848] [INFO] Worker exiting (pid: 1848)
[2017-02-21 10:37:49 +0000] [1843] [INFO] Shutting down: Master
[2017-02-21 10:37:49 +0000] [1843] [INFO] Reason: Worker failed to boot.

**Comment by xiaoyuge16** [comment]
我也遇到了同样的问题，请问应该怎么办呢？ @HatBoy 

你的问题解决了吗？ @gitfuzzing

**Comment by HatBoy** [comment]
import geoip2.database
ImportError: No module named geoip2.database
你们是否安装了geoip2这个第三方库？

**Comment by xiaoyuge16** [comment]
谢谢，安装后就好了~

发自我的 iPhone

**Comment by PokerMonster** [comment]
[root@localhost Pcap-Analyzer]# gunicorn -c deploy_config.py run:app
[2019-06-13 00:46:22 -0700] [78427] [DEBUG] Current configuration:
  config: deploy_config.py
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /projet/pcap-analyzer/Pcap-Analyzer
  daemon: False
  raw_env: []
  pidfile: /var/log/gunicorn/debug.log
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: gunicorn.pid
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f72e6bdf048>
  on_reload: <function OnReload.on_reload at 0x7f72e6bdf158>
  when_ready: <function WhenReady.when_ready at 0x7f72e6bdf268>
  pre_fork: <function Prefork.pre_fork at 0x7f72e6bdf378>
  post_fork: <function Postfork.post_fork at 0x7f72e6bdf488>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f72e6bdf598>
  worker_int: <function WorkerInt.worker_int at 0x7f72e6bdf6a8>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f72e6bdf7b8>
  pre_exec: <function PreExec.pre_exec at 0x7f72e6bdf8c8>
  pre_request: <function PreRequest.pre_request at 0x7f72e6bdf9d8>
  post_request: <function PostRequest.post_request at 0x7f72e6bdfa60>
  child_exit: <function ChildExit.child_exit at 0x7f72e6bdfb70>
  worker_exit: <function WorkerExit.worker_exit at 0x7f72e6bdfc80>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f72e6bdfd90>
  on_exit: <function OnExit.on_exit at 0x7f72e6bdfea0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-06-13 00:46:22 -0700] [78427] [INFO] Starting gunicorn 19.9.0
[2019-06-13 00:46:22 -0700] [78427] [DEBUG] Arbiter booted
[2019-06-13 00:46:22 -0700] [78427] [INFO] Listening at: http://0.0.0.0:8000 (78427)
[2019-06-13 00:46:22 -0700] [78427] [INFO] Using worker: sync
[2019-06-13 00:46:22 -0700] [78430] [INFO] Booting worker with pid: 78430
[2019-06-13 00:46:22 -0700] [78427] [DEBUG] 1 workers
[2019-06-13 00:46:22 -0700] [78430] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/projet/pcap-analyzer/Pcap-Analyzer/run.py", line 4, in <module>
    from app import app
  File "/projet/pcap-analyzer/Pcap-Analyzer/app/__init__.py", line 11, in <module>
    from app import views
  File "/projet/pcap-analyzer/Pcap-Analyzer/app/views.py", line 8, in <module>
    from .utils.pcap_decode import PcapDecode
  File "/projet/pcap-analyzer/Pcap-Analyzer/app/utils/pcap_decode.py", line 4, in <module>
    from scapy.all import *
  File "/usr/local/lib/python3.7/site-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/usr/local/lib/python3.7/site-packages/scapy/arch/__init__.py", line 56, in <module>
    from scapy.arch.linux import *  # noqa F403
  File "/usr/local/lib/python3.7/site-packages/scapy/arch/linux.py", line 28, in <module>
    from scapy.packet import Packet, Padding
  File "/usr/local/lib/python3.7/site-packages/scapy/packet.py", line 28, in <module>
    from scapy.extlib import PYX
  File "/usr/local/lib/python3.7/site-packages/scapy/extlib.py", line 54, in <module>
    if _test_pyx():
  File "/usr/local/lib/python3.7/site-packages/scapy/extlib.py", line 45, in _test_pyx
    stdout=devnull, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex': 'pdflatex'
[2019-06-13 00:46:22 -0700] [78430] [INFO] Worker exiting (pid: 78430)
[2019-06-13 00:46:22 -0700] [78427] [INFO] Shutting down: Master
[2019-06-13 00:46:22 -0700] [78427] [INFO] Reason: Worker failed to boot.

系统是 centos 7.2
python 版本是 3.7.2
请问出现这个错误怎么解决， 我已经尝试安装 pdflatex 和 latex，还是一样这个错误。

**Comment by netspaces** [comment]
> [root@localhost Pcap-Analyzer]# gunicorn -c deploy_config.py run:app
> [2019-06-13 00:46:22 -0700] [78427] [DEBUG] Current configuration:
> config: deploy_config.py
> bind: ['0.0.0.0:8000']
> backlog: 2048
> workers: 1
> worker_class: sync
> threads: 1
> worker_connections: 1000
> max_requests: 0
> max_requests_jitter: 0
> timeout: 30
> graceful_timeout: 30
> keepalive: 2
> limit_request_line: 4094
> limit_request_fields: 100
> limit_request_field_size: 8190
> reload: False
> reload_engine: auto
> reload_extra_files: []
> spew: False
> check_config: False
> preload_app: False
> sendfile: None
> reuse_port: False
> chdir: /projet/pcap-analyzer/Pcap-Analyzer
> daemon: False
> raw_env: []
> pidfile: /var/log/gunicorn/debug.log
> worker_tmp_dir: None
> user: 0
> group: 0
> umask: 0
> initgroups: False
> tmp_upload_dir: None
> secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
> forwarded_allow_ips: ['127.0.0.1']
> accesslog: None
> disable_redirect_access_to_syslog: False
> access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
> errorlog: -
> loglevel: debug
> capture_output: False
> logger_class: gunicorn.glogging.Logger
> logconfig: None
> logconfig_dict: {}
> syslog_addr: udp://localhost:514
> syslog: False
> syslog_prefix: None
> syslog_facility: user
> enable_stdio_inheritance: False
> statsd_host: None
> statsd_prefix:
> proc_name: gunicorn.pid
> default_proc_name: run:app
> pythonpath: None
> paste: None
> on_starting: <function OnStarting.on_starting at 0x7f72e6bdf048>
> on_reload: <function OnReload.on_reload at 0x7f72e6bdf158>
> when_ready: <function WhenReady.when_ready at 0x7f72e6bdf268>
> pre_fork: <function Prefork.pre_fork at 0x7f72e6bdf378>
> post_fork: <function Postfork.post_fork at 0x7f72e6bdf488>
> post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f72e6bdf598>
> worker_int: <function WorkerInt.worker_int at 0x7f72e6bdf6a8>
> worker_abort: <function WorkerAbort.worker_abort at 0x7f72e6bdf7b8>
> pre_exec: <function PreExec.pre_exec at 0x7f72e6bdf8c8>
> pre_request: <function PreRequest.pre_request at 0x7f72e6bdf9d8>
> post_request: <function PostRequest.post_request at 0x7f72e6bdfa60>
> child_exit: <function ChildExit.child_exit at 0x7f72e6bdfb70>
> worker_exit: <function WorkerExit.worker_exit at 0x7f72e6bdfc80>
> nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f72e6bdfd90>
> on_exit: <function OnExit.on_exit at 0x7f72e6bdfea0>
> proxy_protocol: False
> proxy_allow_ips: ['127.0.0.1']
> keyfile: None
> certfile: None
> ssl_version: 2
> cert_reqs: 0
> ca_certs: None
> suppress_ragged_eofs: True
> do_handshake_on_connect: False
> ciphers: TLSv1
> raw_paste_global_conf: []
> [2019-06-13 00:46:22 -0700] [78427] [INFO] Starting gunicorn 19.9.0
> [2019-06-13 00:46:22 -0700] [78427] [DEBUG] Arbiter booted
> [2019-06-13 00:46:22 -0700] [78427] [INFO] Listening at: http://0.0.0.0:8000 (78427)
> [2019-06-13 00:46:22 -0700] [78427] [INFO] Using worker: sync
> [2019-06-13 00:46:22 -0700] [78430] [INFO] Booting worker with pid: 78430
> [2019-06-13 00:46:22 -0700] [78427] [DEBUG] 1 workers
> [2019-06-13 00:46:22 -0700] [78430] [ERROR] Exception in worker process
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> worker.init_process()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
> self.load_wsgi()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
> self.wsgi = self.app.wsgi()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> self.callable = self.load()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
> return self.load_wsgiapp()
> File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
> return util.import_app(self.app_uri)
> File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
> **import**(module)
> File "/projet/pcap-analyzer/Pcap-Analyzer/run.py", line 4, in 
> from app import app
> File "/projet/pcap-analyzer/Pcap-Analyzer/app/**init**.py", line 11, in 
> from app import views
> File "/projet/pcap-analyzer/Pcap-Analyzer/app/views.py", line 8, in 
> from .utils.pcap_decode import PcapDecode
> File "/projet/pcap-analyzer/Pcap-Analyzer/app/utils/pcap_decode.py", line 4, in 
> from scapy.all import *
> File "/usr/local/lib/python3.7/site-packages/scapy/all.py", line 18, in 
> from scapy.arch import *
> File "/usr/local/lib/python3.7/site-packages/scapy/arch/**init**.py", line 56, in 
> from scapy.arch.linux import * # noqa F403
> File "/usr/local/lib/python3.7/site-packages/scapy/arch/linux.py", line 28, in 
> from scapy.packet import Packet, Padding
> File "/usr/local/lib/python3.7/site-packages/scapy/packet.py", line 28, in 
> from scapy.extlib import PYX
> File "/usr/local/lib/python3.7/site-packages/scapy/extlib.py", line 54, in 
> if _test_pyx():
> File "/usr/local/lib/python3.7/site-packages/scapy/extlib.py", line 45, in _test_pyx
> stdout=devnull, stderr=subprocess.STDOUT)
> File "/usr/local/lib/python3.7/subprocess.py", line 342, in check_call
> retcode = call(*popenargs, **kwargs)
> File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
> with Popen(*popenargs, **kwargs) as p:
> File "/usr/local/lib/python3.7/subprocess.py", line 775, in **init**
> restore_signals, start_new_session)
> File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex': 'pdflatex'
> [2019-06-13 00:46:22 -0700] [78430] [INFO] Worker exiting (pid: 78430)
> [2019-06-13 00:46:22 -0700] [78427] [INFO] Shutting down: Master
> [2019-06-13 00:46:22 -0700] [78427] [INFO] Reason: Worker failed to boot.
> 
> 系统是 centos 7.2
> python 版本是 3.7.2
> 请问出现这个错误怎么解决， 我已经尝试安装 pdflatex 和 latex，还是一样这个错误。
用这个试一下，你最好用sudo 权限来做
sudo apt install texlive-latex-base

**Comment by netspaces** [comment]
用这个试一下，你最好用sudo权限来做 @PokerMonster 
sudo apt install texlive-latex-base

**Comment by Xia0Ny1** [comment]
[2020-10-15 14:48:54 +0800] [1607] [DEBUG] Current configuration:
  config: deploy_config.py
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/Pcap-Analyzer
  daemon: False
  raw_env: []
  pidfile: /var/log/gunicorn/debug.log
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: gunicorn.pid
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f8f18a5e4c0>
  on_reload: <function OnReload.on_reload at 0x7f8f18a5e5e0>
  when_ready: <function WhenReady.when_ready at 0x7f8f18a5e700>
  pre_fork: <function Prefork.pre_fork at 0x7f8f18a5e820>
  post_fork: <function Postfork.post_fork at 0x7f8f18a5e940>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f8f18a5ea60>
  worker_int: <function WorkerInt.worker_int at 0x7f8f18a5eb80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f8f18a5eca0>
  pre_exec: <function PreExec.pre_exec at 0x7f8f18a5edc0>
  pre_request: <function PreRequest.pre_request at 0x7f8f18a5eee0>
  post_request: <function PostRequest.post_request at 0x7f8f18a5ef70>
  child_exit: <function ChildExit.child_exit at 0x7f8f18a710d0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f8f18a711f0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f8f18a71310>
  on_exit: <function OnExit.on_exit at 0x7f8f18a71430>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-10-15 14:48:54 +0800] [1607] [INFO] Starting gunicorn 20.0.4

Error: /var/log/gunicorn doesn't exist. Can't create pidfile.
