### ISSUE TITLE
不想说啥了，把上传目录设在了内置存储

### ISSUE THREAD

**Issue by w311ang** [HatBoy/Pcap-Analyzer#34]
照片啥的全部都给拜拜了，要不是关得早整个内置存储都删干净了

**Comment by w311ang** [comment]
威力不亚于rm -rf /*

**Comment by xiaoyunjie** [comment]
![image](https://user-images.githubusercontent.com/18340924/87535716-7d884f00-c6ca-11ea-89ca-950a73f6bbc2.png)

**Comment by w311ang** [comment]
> ![image](https://user-images.githubusercontent.com/18340924/87535716-7d884f00-c6ca-11ea-89ca-950a73f6bbc2.png)
> 应该是这边吧，

删库必备啊哭

**Comment by HatBoy** [comment]
@w311ang 很抱歉，由于代码的不严谨，给你带来的麻烦和困扰。已经删除了该行代码。
