### ISSUE TITLE
上传大于50M大小的pcap

### ISSUE THREAD

**Issue by HackPluto** [HatBoy/Pcap-Analyzer#36]
请问修改哪里的代码可以上传大于50M的数据包

**Comment by HatBoy** [comment]
@HackPluto 代码层面并没有对上传数据包的大小进行限制，数据包的解析功能依赖scapy库加载数据包，scapy加载数据包时十分的吃内存，50M的数据包可能需要上G的内存，系统内存不够用会直接杀进程。
