### ISSUE TITLE
Ubuntu18，20环境配置问题

### ISSUE THREAD

**Issue by TooYang-moon** [HatBoy/Pcap-Analyzer#38]
Ubuntu18，20下数据分析时总是出问题。
有用过Ubuntu18，20的朋友吗？排查了一下感觉可能是软件包的版本问题？
请问您的环境配置，每个软件包的版本包括python的版本是多少啊？
还有scapy库可能也有些问题，不知道装没装全？
希望有实验成功的朋友来解答一下疑惑，或者作者@HatBoy朋友能帮忙解答一下。

**Comment by HatBoy** [comment]
@TooYang-moon 具体是什么问题， 编写改代码时Python的版本3.5.X，并没有用到什么高版本的特性，所以即使是现在的3.8.X理论上是兼容的。大概率是scapy版本的问题，编写代码时scapy刚刚移植到Python3，很多功能都不完善，目前的scapy最新版已经和当初的版本有较大的区别。scapy 2.4.0之后出现重大变化，部分API发生改变，请尝试试用scapy 2.4.0版本尝试
