### ISSUE TITLE
Which python version will I use?

### ISSUE THREAD

**Issue by debug0man** [HatBoy/Pcap-Analyzer#4]
Which python version will I use?
Can you run on mac os?
Have you tried?
Thanks.

**Comment by HatBoy** [comment]
@debug0man I use Python2.7.12, I run on ubuntu, I can not run on mac os, but I use scapy lib, if scapy can install on mac os, The pcap-analyzer alsso can run on mac os

**Comment by cxstdio** [comment]
> Which python version will I use?
> Can you run on mac os?
> Have you tried?
> Thanks.

I can run this program with python 3.6.0 on macOS Mojave

**Comment by HatBoy** [comment]
@cxstdio 
Python 3.6.X,
You can run on mac os, because of the core lib scapy 2.4 support mac os
